#!/usr/bin/env bash
# Multi-config OOC synth sweep for SDP=0 vs SDP=1.
# Writes a generated markdown summary under sweep_logs by default.
#
# Knobs (env vars consumed by run_synth.tcl):
#   DIRECTIVE: synth directive (default: default; was AreaOptimized_high)
#   PERIOD_NS: target clock period in ns (default: 4.0 = 250 MHz)
#   POLICY:    enum index passed to l2_cache.POLICY (4 = SRRIP, 5 = GRASP)
#              NOTE: REPLACEMENT_POLICY also still accepted by run_synth.tcl
#              but only takes effect when TOP=l2_top. For TOP=l2_cache use
#              POLICY=N; REPLACEMENT_POLICY does not configure an l2_cache top.
#   VICTIM:    INCLUDE_VICTIM 0|1 (default 1 with VICTIM_LINES=16)
#   DB_LATENCY: cache databank pipeline depth (default 1)
set -u
HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="${OUT:-$HERE/sweep_logs}"
mkdir -p "$OUT"
SUMMARY="${SUMMARY:-$OUT/sweep_summary.md}"
mkdir -p "$(dirname "$SUMMARY")"

POLICY="${POLICY:-4}"          # 4 = SRRIP
VICTIM="${VICTIM:-1}"
VICTIM_LINES="${VICTIM_LINES:-16}"
DB_LATENCY="${DB_LATENCY:-1}"
DIRECTIVE="${DIRECTIVE:-default}"
PERIOD_NS="${PERIOD_NS:-4.0}"

declare -a CONFIGS=(
    "256K_4way:WAYS=4 LINES=512  LINE_W=8"
    "256K_8way:WAYS=8 LINES=512  LINE_W=8"
    "512K_8way:WAYS=8 LINES=1024 LINE_W=16"
    "1M_8way:WAYS=8 LINES=2048 LINE_W=16"
)

{
    echo "# TableCache OOC sweep (U250, ${PERIOD_NS} ns target, directive=${DIRECTIVE})"
    echo
    echo "Auto-generated by syn/vivado/sweep.sh."
    echo "POLICY=${POLICY} (4=SRRIP, 5=GRASP), INCLUDE_VICTIM=${VICTIM}, DB_LATENCY=${DB_LATENCY}."
    echo "Per-run reports under sweep_logs/."
    echo
    echo "| Config | Mode | LUT | FF | BRAM | URAM | WNS (ns) |"
    echo "|--------|------|----:|---:|-----:|-----:|---------:|"
} > "$SUMMARY"

for entry in "${CONFIGS[@]}"; do
    name="${entry%%:*}"
    args="${entry#*:}"
    for mode in TDP SDP; do
        sdp=0; [[ $mode == SDP ]] && sdp=1
        tag="${name}_${mode}"
        echo "==== $tag ($args POLICY=$POLICY DATABANK_SDP=$sdp DB_LATENCY=$DB_LATENCY VICTIM=$VICTIM dir=$DIRECTIVE period=${PERIOD_NS}ns) ===="
        rm -rf "$HERE/build/l2_cache"
        eval "$args" DATABANK_SDP=$sdp POLICY=$POLICY \
             INCLUDE_VICTIM=$VICTIM VICTIM_LINES=$VICTIM_LINES \
             DB_LATENCY=$DB_LATENCY DIRECTIVE=$DIRECTIVE PERIOD_NS=$PERIOD_NS \
             TOP=l2_cache \
            timeout 1800 "$HERE/run_synth.sh" > "$OUT/${tag}.log" 2>&1
        rc=$?
        if [[ $rc -ne 0 ]] || [[ ! -f "$HERE/build/l2_cache/utilization.rpt" ]]; then
            echo "  FAILED (rc=$rc)"
            echo "| $name | $mode | FAIL | - | - | - | - |" >> "$SUMMARY"
            continue
        fi
        # Snapshot reports
        cp "$HERE/build/l2_cache/utilization.rpt"   "$OUT/${tag}_util.rpt"
        cp "$HERE/build/l2_cache/timing_summary.rpt" "$OUT/${tag}_timing.rpt"
        # Parse headline numbers
        lut=$(grep -E "^\\| CLB LUTs\\*" "$OUT/${tag}_util.rpt" | awk -F'|' '{gsub(/ /,"",$3); print $3}')
        ff=$(grep -E "^\\| CLB Registers" "$OUT/${tag}_util.rpt" | awk -F'|' '{gsub(/ /,"",$3); print $3}')
        bram=$(grep -E "^\\| Block RAM Tile" "$OUT/${tag}_util.rpt" | awk -F'|' '{gsub(/ /,"",$3); print $3}')
        uram=$(grep -E "^\\| URAM " "$OUT/${tag}_util.rpt" | awk -F'|' '{gsub(/ /,"",$3); print $3}')
        # First WNS field from the Design Timing Summary table (works for MET or VIOLATED)
        wns=$(awk '/^    WNS\(ns\)/{getline; getline; print $1; exit}' "$OUT/${tag}_timing.rpt")
        echo "  LUT=$lut FF=$ff BRAM=$bram URAM=$uram WNS=$wns"
        echo "| $name | $mode | $lut | $ff | $bram | $uram | $wns |" >> "$SUMMARY"
    done
done

echo
echo "==== Summary written to $SUMMARY ===="
cat "$SUMMARY"
