#!/usr/bin/env bash
# Multi-config OOC synth sweep for SDP=0 vs SDP=1.
# Drops a markdown table summary at $HERE/sweep_results.md
set -u
HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/sweep_logs"
mkdir -p "$OUT"
SUMMARY="$HERE/sweep_results.md"

declare -a CONFIGS=(
    "256K_4way:WAYS=4 LINES=512  LINE_W=8"
    "256K_8way:WAYS=8 LINES=512  LINE_W=8"
    "512K_8way:WAYS=8 LINES=1024 LINE_W=16"
    "1M_8way:WAYS=8 LINES=2048 LINE_W=16"
)

{
    echo "# TableCache OOC sweep (U250, 250 MHz target, AreaOptimized_high)"
    echo
    echo "Auto-generated by syn/vivado/sweep.sh. Per-run reports under sweep_logs/."
    echo
    echo "| Config | Mode | LUT | FF | BRAM | URAM | WNS (ns) |"
    echo "|--------|------|----:|---:|-----:|-----:|---------:|"
} > "$SUMMARY"

for entry in "${CONFIGS[@]}"; do
    name="${entry%%:*}"
    args="${entry#*:}"
    for mode in TDP SDP; do
        sdp=0; [[ $mode == SDP ]] && sdp=1
        tag="${name}_${mode}"
        echo "==== $tag ($args DATABANK_SDP=$sdp) ===="
        rm -rf "$HERE/build/l2_cache"
        eval "$args" DATABANK_SDP=$sdp REPLACEMENT_POLICY=4 INCLUDE_VICTIM=1 VICTIM_LINES=16 TOP=l2_cache \
            timeout 1800 "$HERE/run_synth.sh" > "$OUT/${tag}.log" 2>&1
        rc=$?
        if [[ $rc -ne 0 ]] || [[ ! -f "$HERE/build/l2_cache/utilization.rpt" ]]; then
            echo "  FAILED (rc=$rc)"
            echo "| $name | $mode | FAIL | - | - | - | - |" >> "$SUMMARY"
            continue
        fi
        # Snapshot reports
        cp "$HERE/build/l2_cache/utilization.rpt"   "$OUT/${tag}_util.rpt"
        cp "$HERE/build/l2_cache/timing_summary.rpt" "$OUT/${tag}_timing.rpt"
        # Parse headline numbers
        lut=$(grep -E "^\\| CLB LUTs\\*" "$OUT/${tag}_util.rpt" | awk -F'|' '{gsub(/ /,"",$3); print $3}')
        ff=$(grep -E "^\\| CLB Registers" "$OUT/${tag}_util.rpt" | awk -F'|' '{gsub(/ /,"",$3); print $3}')
        bram=$(grep -E "^\\| Block RAM Tile" "$OUT/${tag}_util.rpt" | awk -F'|' '{gsub(/ /,"",$3); print $3}')
        uram=$(grep -E "^\\| URAM " "$OUT/${tag}_util.rpt" | awk -F'|' '{gsub(/ /,"",$3); print $3}')
        wns=$(awk '/Design Timing Summary/,/All user/' "$OUT/${tag}_timing.rpt" | awk 'NR==4 {print $1}')
        echo "  LUT=$lut FF=$ff BRAM=$bram URAM=$uram WNS=$wns"
        echo "| $name | $mode | $lut | $ff | $bram | $uram | $wns |" >> "$SUMMARY"
    done
done

echo
echo "==== Summary written to $SUMMARY ===="
cat "$SUMMARY"
