#!/usr/bin/env bash
# GRASP-path hardening sweep. Mirrors sdp_stress.sh structure.
# Drops a markdown summary at $OUT/summary.md.
#
# Knobs: OUT (default /tmp/tc_grasp_stress), N_SEEDS (30), NTXN (100),
#        PERF_NTXN (5000), QUICK=1 (skip extended checks)
set -u
HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="${OUT:-/tmp/tc_grasp_stress}"
N_SEEDS="${N_SEEDS:-30}"
NTXN="${NTXN:-100}"
PERF_NTXN="${PERF_NTXN:-5000}"
QUICK="${QUICK:-0}"
mkdir -p "$OUT"
SUMMARY="$OUT/summary.md"

cd "$HERE"
source .venv/bin/activate

ts() { date +%H:%M:%S; }

{
    echo "# GRASP-path hardening sweep"
    echo
    echo "Generated by \`tb/cocotb/grasp_stress.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
    echo "Config: N_SEEDS=$N_SEEDS NTXN=$NTXN PERF_NTXN=$PERF_NTXN QUICK=$QUICK"
    echo
    echo "| Check | Test | Result |"
    echo "|---|---|---|"
} > "$SUMMARY"

global_fail=0
record() {
    local check="$1"; local test="$2"; local result="$3"
    echo "| $check | $test | $result |" >> "$SUMMARY"
    if [[ "$result" != *"PASS"* && "$result" != *"clean"* && "$result" != *"OK"* ]]; then
        global_fail=$((global_fail+1))
    fi
}

echo "[$(ts)] static lint"
if make vlint > "$OUT/lint.log" 2>&1; then
    record lint "verible" "clean"
else
    record lint "verible" "FAIL"
fi

echo "[$(ts)] policy comparison ($PERF_NTXN transactions)"
POLICIES=LRU,SRRIP,GRASP,RANDOM NTXN=$PERF_NTXN OUT="$OUT/perf" make perf \
    > "$OUT/performance.log" 2>&1
if [[ -f "$OUT/perf/summary.md" ]] || grep -qE "GRASP\s+\|" "$OUT/performance.log"; then
    lru=$(grep -oE 'LRU\s+\|\s+[0-9.]+%' "$OUT/performance.log" | head -1 | grep -oE '[0-9.]+')
    srrip=$(grep -oE 'SRRIP\s+\|\s+[0-9.]+%' "$OUT/performance.log" | head -1 | grep -oE '[0-9.]+')
    grasp=$(grep -oE 'GRASP\s+\|\s+[0-9.]+%' "$OUT/performance.log" | head -1 | grep -oE '[0-9.]+')
    rnd=$(grep -oE 'RANDOM\s+\|\s+[0-9.]+%' "$OUT/performance.log" | head -1 | grep -oE '[0-9.]+')
    # Ordering check: GRASP >= RANDOM (GRASP without configured regions == SRRIP-FP, must
    # at minimum beat random). Skip if any field is missing.
    if [[ -n "$grasp" && -n "$rnd" ]] && \
       awk -v g="$grasp" -v r="$rnd" 'BEGIN{exit !(g>=r-0.5)}'; then
        record performance "policy comparison" "PASS (LRU=$lru% SRRIP=$srrip% GRASP=$grasp% RANDOM=$rnd%)"
    else
        record performance "policy comparison" "FAIL (GRASP=$grasp% should be >= RANDOM=$rnd%)"
    fi
else
    record performance "policy comparison" "FAIL (no output)"
fi

echo "[$(ts)] X-propagation checks"
for mod in test_grasp test_workload test_random; do
    rm -rf sim_build
    log="$OUT/xprop_${mod}.log"
    if XPROP=1 POLICY=GRASP timeout 600 make MODULE=$mod > "$log" 2>&1 && \
       grep -qE 'TESTS=[0-9]+.*PASS=[0-9]+.*FAIL=0' "$log"; then
        record xprop "$mod" "PASS"
    else
        record xprop "$mod" "FAIL"
    fi
done

if [[ "$QUICK" == "1" ]]; then
    echo "[$(ts)] QUICK=1, skipping extended checks"
    {
        echo
        echo "Extended checks skipped."
        echo
        echo "## Summary: $([ $global_fail -eq 0 ] && echo 'ALL PASS' || echo "$global_fail FAILURES")"
    } >> "$SUMMARY"
    cat "$SUMMARY"
    exit $([ $global_fail -eq 0 ] && echo 0 || echo 1)
fi

echo "[$(ts)] associativity sweep"
for mod in test_grasp test_workload; do
    for ways in 2 4 8; do
        rm -rf sim_build
        log="$OUT/ways${ways}_${mod}.log"
        if WAYS=$ways POLICY=GRASP timeout 600 make MODULE=$mod > "$log" 2>&1 && \
           grep -qE 'TESTS=[0-9]+.*PASS=[0-9]+.*FAIL=0' "$log"; then
            record associativity "WAYS=$ways $mod" "PASS"
        else
            record associativity "WAYS=$ways $mod" "FAIL"
        fi
    done
done

echo "[$(ts)] random seed sweep: $N_SEEDS seeds"
p5_pass=0; p5_fail=0
for seed in $(seq 1 $N_SEEDS); do
    rm -rf sim_build
    log="$OUT/seed_${seed}.log"
    if POLICY=GRASP SEED=$seed NTXN=$NTXN timeout 120 make MODULE=test_random > "$log" 2>&1 && \
       grep -qE 'TESTS=[0-9]+.*PASS=[0-9]+.*FAIL=0' "$log"; then
        p5_pass=$((p5_pass+1))
    else
        p5_fail=$((p5_fail+1))
        echo "  seed $seed FAIL"
    fi
    if (( seed % 10 == 0 )); then
        echo "  progress: $seed/$N_SEEDS  pass=$p5_pass fail=$p5_fail"
    fi
done
if [[ $p5_fail -eq 0 ]]; then
    record seeds "test_random ($N_SEEDS seeds)" "PASS ($p5_pass/$N_SEEDS)"
else
    record seeds "test_random ($N_SEEDS seeds)" "FAIL ($p5_pass pass / $p5_fail fail)"
fi

echo "[$(ts)] TDP and SDP regression"
for sdp in 0 1; do
    extra=""
    [[ $sdp == 1 ]] && extra="+define+TC_DATABANK_SDP=1"
    for mod in test_smoke test_grasp test_random test_scoreboard test_workload \
               test_reset_recovery test_backpressure test_strobe test_latency; do
        rm -rf sim_build
        log="$OUT/sdp${sdp}_${mod}.log"
        if EXTRA_ARGS="$extra" POLICY=GRASP timeout 600 make MODULE=$mod > "$log" 2>&1 && \
           grep -qE 'TESTS=[0-9]+.*PASS=[0-9]+.*FAIL=0' "$log"; then
            record storage "SDP=$sdp $mod" "PASS"
        else
            record storage "SDP=$sdp $mod" "FAIL"
        fi
    done
done

# ----------------------------------------------------------------------
# Summary
# ----------------------------------------------------------------------
{
    echo
    if [[ $global_fail -eq 0 ]]; then
        echo "## Result: ALL PASS"
    else
        echo "## Result: $global_fail FAILURE(S) -- inspect logs under $OUT/"
    fi
} >> "$SUMMARY"

cat "$SUMMARY"
exit $([ $global_fail -eq 0 ] && echo 0 || echo 1)
